# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7ef44d3f24a3abfe04ee0cc86aea6362d323eb8956181f46398f0d6bfb3eaf98d63e8dda4f4c5dc05925d815908c0a7f234b393501b71fb6f015de4b099fbcf

test:
  secret_key_base: 6e17a1ef7aaf90ebb9110b11bc03ebb1700d5d8c4408a63abb7a70b56e204856277e904a147260662faf59d8a51ab4a3cb5a8ee903b704e7e32b2e37089867cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
